apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
  - git:
      repoURL: https://github.com/kylecrawshaw/argocd-applicationset-demo.git
      revision: HEAD
      files:
      - path: "k8s/prod/cluster-config-*.json"
  template:
    metadata:
      name: 'guestbook{{appSuffix}}'
      labels:
        "deploy-ops.app": "guestbook"
        "deploy-ops.project": "guestbook"
    spec:
      project: default
      source:
        repoURL: https://github.com/kylecrawshaw/argocd-applicationset-demo.git
        targetRevision: HEAD
        path: "k8s"
        helm:
          valueFiles:
            - values.yaml
            - '{{environment}}/values-{{region}}.yaml'
      destination:
        server: https://kubernetes.default.svc
        #server: '{{cluster.address}}'
        namespace: guestbook-{{cluster.name}}
      syncPolicy:
        syncOptions:
          - CreateNamespace=false
